# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
fastlane_version "2.46.0"
import_from_git(url: 'git@gitlab.com:madbrains/util/fastlane-scripts.git', branch: 'v2', path: 'Fastfile')

default_platform :android

platform :android do

lane :firebase_inspection do
	firebase(
		firebase_app_id: '1:714037425430:android:cf4d7312d242c58aff0c37',
		test_groups: 'madbrains'
	)
end

end
