import_from_git(url: 'git@gitlab.com:madbrains/util/fastlane-scripts.git', branch: 'v2', path: 'Fastfile')

default_platform :android

platform :android do

lane :firebase_inspection do
	firebase(
		firebase_app_id: '1:714037425430:android:cf4d7312d242c58aff0c37',
		test_groups: 'madbrains'
	)
end

end
